spring:
  application:
    name: swagger-api

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true

springdoc:
  swagger-ui:
    display-request-duration: true

com:
  katsiankou:
    downstream:
      nbrb-api-url: https://api.nbrb.by
    swagger:
      api-title: NBRB API wrapper
      version: 1.0
      description: API documentation for a wrapper on NBRB API
    cache:
      config:
        - name: currency-rates
          expire-after-write-hours: 12
          maximum-size: 500
        - name: currencies
          expire-after-write-hours: 24
          maximum-size: 500